# Generated by Django 5.2.3 on 2025-07-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forca', '0002_jogada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tema',
            name='login_obrigatorio',
            field=models.BooleanField(default=False),
        ),
    ]
