# Generated by Django 5.2.3 on 2025-07-08 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forca', '0003_professor_tema_login_obrigatorio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palavra',
            name='texto_extra',
        ),
        migrations.AlterField(
            model_name='palavra',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='palavra',
            name='texto',
            field=models.CharField(max_length=100),
        ),
    ]
